import type { Company } from "./types.js";

export const SCHEDULE_HOURS = 6;

export const PROFILE = {
  years: 4,
  preferredLocations: [
    "india",
    "bengaluru",
    "bangalore",
    "hyderabad",
    "pune",
    "chennai",
    "noida",
    "gurugram",
    "gurgaon",
    "mumbai",
    "remote",
  ],
  skills: [
    "react",
    "typescript",
    "javascript",
    "angular",
    "redux",
    "context api",
    "html5",
    "css3",
    "design system",
    "component library",
    "accessibility",
    "wcag",
    "performance",
    "webpack",
    "vite",
    "jest",
    "react testing library",
    "rest",
    "websocket",
    "opentelemetry",
  ],
};

// Each entry points to the company's current official career system. HTML sources
// are deliberately limited to explicit job-detail URL patterns.
export const COMPANIES: Company[] = [
  {
    id: "cred",
    name: "CRED",
    source: "lever",
    token: "cred",
    careerUrl: "https://careers.cred.club/openings",
    enabled: true,
  },
  {
    id: "practo",
    name: "Practo",
    source: "html",
    listUrls: ["https://careers.practo.com/practo/"],
    jobLinkPattern: "careers\\.practo\\.com/.+/(?:job|jobs|opening|openings)/|careers\\.practo\\.com/practo/.+\\d",
    emptyIsHealthy: true,
    careerUrl: "https://careers.practo.com/practo/",
    enabled: true,
  },
  {
    id: "observe-ai",
    name: "Observe.AI",
    source: "greenhouse",
    token: "observeai",
    careerUrl: "https://www.observe.ai/careers",
    enabled: true,
  },
  {
    id: "jpmc",
    name: "JPMorgan Chase",
    source: "oracle",
    host: "https://jpmc.fa.oraclecloud.com",
    siteNumber: "CX_1001",
    careerUrl: "https://jpmc.fa.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001/requisitions",
    enabled: true,
  },
  {
    id: "microsoft",
    name: "Microsoft",
    source: "html",
    listUrls: [
      "https://careers.microsoft.com/professionals/us/en/l-india",
      "https://careers.microsoft.com/v2/global/en/locations/bengaluru.html",
      "https://careers.microsoft.com/v2/global/en/locations/hyderabad.html",
    ],
    jobLinkPattern: "apply\\.careers\\.microsoft\\.com/careers/job/",
    careerUrl: "https://apply.careers.microsoft.com/careers?location=India&hl=en",
    enabled: true,
  },
  {
    id: "cadence",
    name: "Cadence",
    source: "workday",
    host: "https://cadence.wd1.myworkdayjobs.com",
    tenant: "cadence",
    site: "External_Careers",
    careerUrl: "https://cadence.wd1.myworkdayjobs.com/External_Careers",
    enabled: true,
  },
  {
    id: "jiohotstar",
    name: "JioHotstar",
    source: "workday",
    host: "https://jiostar.wd102.myworkdayjobs.com",
    tenant: "jiostar",
    site: "JioStar",
    careerUrl: "https://jiostar.wd102.myworkdayjobs.com/JioStar",
    enabled: true,
  },
  {
    id: "ibm-isl",
    name: "IBM ISL",
    source: "html",
    listUrls: ["https://www.ibm.com/careers/search?location=India"],
    jobLinkPattern: "careers\\.ibm\\.com/.+(?:JobDetail|job)/",
    emptyIsHealthy: true,
    careerUrl: "https://www.ibm.com/careers/search?location=India",
    enabled: true,
  },
  {
    id: "ameriprise",
    name: "Ameriprise",
    source: "html",
    listUrls: [
      "https://careers.ameriprise.com/our-brands/ameriprise-india/",
      "https://careers.ameriprise.com/search-jobs/?keyword=frontend",
      "https://careers.ameriprise.com/search-jobs/?keyword=react",
    ],
    jobLinkPattern: "careers\\.ameriprise\\.com/search-jobs/[a-z0-9_-]+/",
    careerUrl: "https://careers.ameriprise.com/our-brands/ameriprise-india/",
    enabled: true,
  },
  {
    id: "walmart",
    name: "Walmart",
    source: "workday",
    host: "https://walmart.wd5.myworkdayjobs.com",
    tenant: "walmart",
    site: "WalmartExternal",
    careerUrl: "https://careers.walmart.com/results?q=frontend&location=India",
    enabled: true,
  },
  {
    id: "cohesity",
    name: "Cohesity",
    source: "workday",
    host: "https://cohesity.wd5.myworkdayjobs.com",
    tenant: "cohesity",
    site: "Cohesity_Careers",
    careerUrl: "https://www.cohesity.com/careers/open-positions/",
    enabled: true,
  },
  {
    id: "nutanix",
    name: "Nutanix",
    source: "html",
    listUrls: ["https://careers.nutanix.com/sitemap.xml"],
    jobLinkPattern: "careers\\.nutanix\\.com/(?:en/)?jobs/\\d+",
    careerUrl: "https://careers.nutanix.com/en/jobs/?country=India",
    enabled: true,
  },
  {
    id: "societe-generale",
    name: "Societe Generale",
    source: "html",
    listUrls: ["https://careers.societegenerale.com/en/Technical/all-job-offers"],
    jobLinkPattern: "careers\\.societegenerale\\.com/en/job-offers/",
    careerUrl: "https://careers.societegenerale.com/en/Technical/all-job-offers",
    enabled: true,
  },
  {
    id: "cisco",
    name: "Cisco",
    source: "html",
    listUrls: [
      "https://jobs.cisco.com/jobs/SearchJobs/java?source=Cisco+Jobs+Career+Site",
      "https://jobs.cisco.com/jobs/SearchJobs/react?source=Cisco+Jobs+Career+Site",
      "https://careers.cisco.com/global/en/search-results?keywords=frontend",
    ],
    jobLinkPattern: "(?:jobs|careers)\\.cisco\\.com/.+(?:ProjectDetail|job)/",
    emptyIsHealthy: true,
    careerUrl: "https://careers.cisco.com/global/en/search-results",
    enabled: true,
  },
  {
    id: "nike",
    name: "Nike",
    source: "html",
    listUrls: [
      "https://careers.nike.com/jobs?location_name=India&location_type=4",
      "https://careers.nike.com/jobs/page/1?location_name=India&location_type=4",
    ],
    jobLinkPattern: "careers\\.nike\\.com/(?:[a-z-]+/)?[^/]+/job/R-",
    careerUrl: "https://careers.nike.com/jobs?location_name=India&location_type=4",
    enabled: true,
  },
  {
    id: "thoughtworks",
    name: "Thoughtworks",
    source: "html",
    listUrls: ["https://www.thoughtworks.com/en-in/careers/jobs"],
    jobLinkPattern: "thoughtworks\\.com/(?:en-in/)?careers/jobs/\\d+",
    emptyIsHealthy: true,
    careerUrl: "https://www.thoughtworks.com/en-in/careers/jobs",
    enabled: true,
  },
  {
    id: "ather",
    name: "Ather",
    source: "html",
    listUrls: ["https://careers.atherenergy.com/jobs?weekdayJdUid=247705"],
    jobLinkPattern: "careers\\.atherenergy\\.com/job/",
    careerUrl: "https://careers.atherenergy.com/jobs",
    enabled: true,
  },
  {
    id: "target",
    name: "Target",
    source: "html",
    listUrls: [
      "https://indiajobs.target.com/search-jobs?fl=1269750&k=frontend",
      "https://indiajobs.target.com/search-jobs?fl=1269750&k=react",
      "https://indiajobs.target.com/search-jobs?fl=1269750&k=software%20engineer",
    ],
    jobLinkPattern: "(?:indiajobs\\.target\\.com/job/|corporate\\.target\\.com/jobs/)",
    careerUrl: "https://indiajobs.target.com/search-jobs?fl=1269750&k=frontend",
    enabled: true,
  },
];
